### ISSUE TITLE
simGL does not seem to be a good name...

### ISSUE THREAD

**Issue by MoiColl** [RacimoLab/simGL#15]
I googled "simGL" and it appears that there is a GitHub repository already with this name (https://github.com/numpad/simgl). Besides, it seems to be a name (there are instagram, twitter and youtube accounts with this name). I suggest we rename it.

**Comment by grahamgower** [comment]
Yeah, naming things is hard. But I think simGL is probably fine. It's short, has relatively few hits on [google](https://www.google.com/search?q=simgl) (23,000 or so for me), the name is available in both [pypi](https://pypi.org/search/?q=simgl) and on [anaconda](https://anaconda.org/search?q=simgl). The github repostory you link to doesn't seem to be an active project, and is not likely to have (m)any users.

**Comment by grahamgower** [comment]
Basically, I think almost any shortish name you think of will be in use for something already.
